apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: shopcloud
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: shopcloud
spec:
  selector:
    app: product-service
  ports:
    - port: 3001
      targetPort: 3001
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: shopcloud
spec:
  selector:
    app: order-service
  ports:
    - port: 3002
      targetPort: 3002
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: shopcloud
spec:
  selector:
    app: user-service
  ports:
    - port: 3003
      targetPort: 3003
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: shopcloud
spec:
  selector:
    app: payment-service
  ports:
    - port: 3004
      targetPort: 3004
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: shopcloud
spec:
  selector:
    app: notification-service
  ports:
    - port: 3005
      targetPort: 3005
  type: ClusterIP
